/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupSecurityQuestionRouteImport } from './routes/setup-security-question'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SerialsIndexRouteImport } from './routes/serials/index'
import { Route as MusicIndexRouteImport } from './routes/music/index'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as CinemaIndexRouteImport } from './routes/cinema/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsGenresRouteImport } from './routes/settings/genres'
import { Route as SettingsFavoritesRouteImport } from './routes/settings/favorites'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsBlockedRouteImport } from './routes/settings/blocked'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as SerialsTmdbIdRouteImport } from './routes/serials/$tmdbId'
import { Route as MusicMbidRouteImport } from './routes/music/$mbid'
import { Route as FilmsTmdbIdRouteImport } from './routes/films/$tmdbId'
import { Route as DirectorSlugRouteImport } from './routes/director/$slug'
import { Route as CinemaTmdbIdRouteImport } from './routes/cinema/$tmdbId'
import { Route as BooksVolumeIdRouteImport } from './routes/books/$volumeId'
import { Route as ActorSlugRouteImport } from './routes/actor/$slug'
import { Route as AuthLayoutRegisterRouteImport } from './routes/_authLayout/register'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as AuthLayoutForgotPasswordRouteImport } from './routes/_authLayout/forgot-password'
import { Route as ProfileUsernameRouteRouteImport } from './routes/profile/$username/route'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ReviewsUsernameReviewIdRouteImport } from './routes/reviews/$username/$reviewId'
import { Route as ProfileUsernameWatchlistRouteImport } from './routes/profile/$username/watchlist'
import { Route as ProfileUsernameWatchingRouteImport } from './routes/profile/$username/watching'
import { Route as ProfileUsernameStatsRouteImport } from './routes/profile/$username/stats'
import { Route as ProfileUsernameReviewsRouteImport } from './routes/profile/$username/reviews'
import { Route as ProfileUsernameLikedRouteImport } from './routes/profile/$username/liked'
import { Route as ProfileUsernameFilmsRouteImport } from './routes/profile/$username/films'
import { Route as ProfileUsernameDiaryRouteImport } from './routes/profile/$username/diary'
import { Route as ProfileUsernameCinemaRouteImport } from './routes/profile/$username/cinema'
import { Route as MusicTracksMbidRouteImport } from './routes/music/tracks/$mbid'
import { Route as ProfileUsernameListsIndexRouteImport } from './routes/profile/$username/lists/index'
import { Route as ProfileUsernameListsNewRouteImport } from './routes/profile/$username/lists/new'
import { Route as ProfileUsernameListsListIdIndexRouteImport } from './routes/profile/$username/lists/$listId/index'
import { Route as ProfileUsernameListsListIdEditRouteImport } from './routes/profile/$username/lists/$listId/edit'

const SetupSecurityQuestionRoute = SetupSecurityQuestionRouteImport.update({
  id: '/setup-security-question',
  path: '/setup-security-question',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SerialsIndexRoute = SerialsIndexRouteImport.update({
  id: '/serials/',
  path: '/serials/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaIndexRoute = CinemaIndexRouteImport.update({
  id: '/cinema/',
  path: '/cinema/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsGenresRoute = SettingsGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFavoritesRoute = SettingsFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsBlockedRoute = SettingsBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SerialsTmdbIdRoute = SerialsTmdbIdRouteImport.update({
  id: '/serials/$tmdbId',
  path: '/serials/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicMbidRoute = MusicMbidRouteImport.update({
  id: '/music/$mbid',
  path: '/music/$mbid',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsTmdbIdRoute = FilmsTmdbIdRouteImport.update({
  id: '/films/$tmdbId',
  path: '/films/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorSlugRoute = DirectorSlugRouteImport.update({
  id: '/director/$slug',
  path: '/director/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaTmdbIdRoute = CinemaTmdbIdRouteImport.update({
  id: '/cinema/$tmdbId',
  path: '/cinema/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksVolumeIdRoute = BooksVolumeIdRouteImport.update({
  id: '/books/$volumeId',
  path: '/books/$volumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorSlugRoute = ActorSlugRouteImport.update({
  id: '/actor/$slug',
  path: '/actor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutForgotPasswordRoute =
  AuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const ProfileUsernameRouteRoute = ProfileUsernameRouteRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ReviewsUsernameReviewIdRoute = ReviewsUsernameReviewIdRouteImport.update({
  id: '/reviews/$username/$reviewId',
  path: '/reviews/$username/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameWatchlistRoute =
  ProfileUsernameWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameWatchingRoute = ProfileUsernameWatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameStatsRoute = ProfileUsernameStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameReviewsRoute = ProfileUsernameReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameLikedRoute = ProfileUsernameLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameFilmsRoute = ProfileUsernameFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameDiaryRoute = ProfileUsernameDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameCinemaRoute = ProfileUsernameCinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const MusicTracksMbidRoute = MusicTracksMbidRouteImport.update({
  id: '/music/tracks/$mbid',
  path: '/music/tracks/$mbid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameListsIndexRoute =
  ProfileUsernameListsIndexRouteImport.update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameListsNewRoute = ProfileUsernameListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameListsListIdIndexRoute =
  ProfileUsernameListsListIdIndexRouteImport.update({
    id: '/lists/$listId/',
    path: '/lists/$listId/',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameListsListIdEditRoute =
  ProfileUsernameListsListIdEditRouteImport.update({
    id: '/lists/$listId/edit',
    path: '/lists/$listId/edit',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/setup-security-question': typeof SetupSecurityQuestionRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/actor/$slug': typeof ActorSlugRoute
  '/books/$volumeId': typeof BooksVolumeIdRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/music/$mbid': typeof MusicMbidRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/blocked': typeof SettingsBlockedRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/cinema/': typeof CinemaIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/serials/': typeof SerialsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/music/tracks/$mbid': typeof MusicTracksMbidRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/stats': typeof ProfileUsernameStatsRoute
  '/profile/$username/watching': typeof ProfileUsernameWatchingRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/new': typeof ProfileUsernameListsNewRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
  '/profile/$username/lists/$listId/edit': typeof ProfileUsernameListsListIdEditRoute
  '/profile/$username/lists/$listId/': typeof ProfileUsernameListsListIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRoute
  '/setup-security-question': typeof SetupSecurityQuestionRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/actor/$slug': typeof ActorSlugRoute
  '/books/$volumeId': typeof BooksVolumeIdRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/music/$mbid': typeof MusicMbidRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/blocked': typeof SettingsBlockedRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/cinema': typeof CinemaIndexRoute
  '/films': typeof FilmsIndexRoute
  '/music': typeof MusicIndexRoute
  '/serials': typeof SerialsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/music/tracks/$mbid': typeof MusicTracksMbidRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/stats': typeof ProfileUsernameStatsRoute
  '/profile/$username/watching': typeof ProfileUsernameWatchingRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/new': typeof ProfileUsernameListsNewRoute
  '/profile/$username/lists': typeof ProfileUsernameListsIndexRoute
  '/profile/$username/lists/$listId/edit': typeof ProfileUsernameListsListIdEditRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/setup-security-question': typeof SetupSecurityQuestionRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/_authLayout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/register': typeof AuthLayoutRegisterRoute
  '/actor/$slug': typeof ActorSlugRoute
  '/books/$volumeId': typeof BooksVolumeIdRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/music/$mbid': typeof MusicMbidRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/blocked': typeof SettingsBlockedRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/cinema/': typeof CinemaIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/serials/': typeof SerialsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/music/tracks/$mbid': typeof MusicTracksMbidRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/stats': typeof ProfileUsernameStatsRoute
  '/profile/$username/watching': typeof ProfileUsernameWatchingRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/new': typeof ProfileUsernameListsNewRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
  '/profile/$username/lists/$listId/edit': typeof ProfileUsernameListsListIdEditRoute
  '/profile/$username/lists/$listId/': typeof ProfileUsernameListsListIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/developer'
    | '/setup-security-question'
    | '/profile/$username'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/actor/$slug'
    | '/books/$volumeId'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/music/$mbid'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/blocked'
    | '/settings/data'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin/'
    | '/books/'
    | '/cinema/'
    | '/films/'
    | '/music/'
    | '/serials/'
    | '/settings/'
    | '/music/tracks/$mbid'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/stats'
    | '/profile/$username/watching'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username/'
    | '/profile/$username/lists/new'
    | '/profile/$username/lists/'
    | '/profile/$username/lists/$listId/edit'
    | '/profile/$username/lists/$listId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer'
    | '/setup-security-question'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/actor/$slug'
    | '/books/$volumeId'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/music/$mbid'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/blocked'
    | '/settings/data'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin'
    | '/books'
    | '/cinema'
    | '/films'
    | '/music'
    | '/serials'
    | '/settings'
    | '/music/tracks/$mbid'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/stats'
    | '/profile/$username/watching'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username'
    | '/profile/$username/lists/new'
    | '/profile/$username/lists'
    | '/profile/$username/lists/$listId/edit'
    | '/profile/$username/lists/$listId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/_authLayout'
    | '/developer'
    | '/setup-security-question'
    | '/profile/$username'
    | '/_authLayout/forgot-password'
    | '/_authLayout/login'
    | '/_authLayout/register'
    | '/actor/$slug'
    | '/books/$volumeId'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/music/$mbid'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/blocked'
    | '/settings/data'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin/'
    | '/books/'
    | '/cinema/'
    | '/films/'
    | '/music/'
    | '/serials/'
    | '/settings/'
    | '/music/tracks/$mbid'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/stats'
    | '/profile/$username/watching'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username/'
    | '/profile/$username/lists/new'
    | '/profile/$username/lists/'
    | '/profile/$username/lists/$listId/edit'
    | '/profile/$username/lists/$listId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DeveloperRoute: typeof DeveloperRoute
  SetupSecurityQuestionRoute: typeof SetupSecurityQuestionRoute
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  ActorSlugRoute: typeof ActorSlugRoute
  BooksVolumeIdRoute: typeof BooksVolumeIdRoute
  CinemaTmdbIdRoute: typeof CinemaTmdbIdRoute
  DirectorSlugRoute: typeof DirectorSlugRoute
  FilmsTmdbIdRoute: typeof FilmsTmdbIdRoute
  MusicMbidRoute: typeof MusicMbidRoute
  SerialsTmdbIdRoute: typeof SerialsTmdbIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CinemaIndexRoute: typeof CinemaIndexRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  MusicIndexRoute: typeof MusicIndexRoute
  SerialsIndexRoute: typeof SerialsIndexRoute
  MusicTracksMbidRoute: typeof MusicTracksMbidRoute
  ReviewsUsernameReviewIdRoute: typeof ReviewsUsernameReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-security-question': {
      id: '/setup-security-question'
      path: '/setup-security-question'
      fullPath: '/setup-security-question'
      preLoaderRoute: typeof SetupSecurityQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/serials/': {
      id: '/serials/'
      path: '/serials'
      fullPath: '/serials/'
      preLoaderRoute: typeof SerialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/': {
      id: '/cinema/'
      path: '/cinema'
      fullPath: '/cinema/'
      preLoaderRoute: typeof CinemaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/genres': {
      id: '/settings/genres'
      path: '/genres'
      fullPath: '/settings/genres'
      preLoaderRoute: typeof SettingsGenresRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/favorites': {
      id: '/settings/favorites'
      path: '/favorites'
      fullPath: '/settings/favorites'
      preLoaderRoute: typeof SettingsFavoritesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/blocked': {
      id: '/settings/blocked'
      path: '/blocked'
      fullPath: '/settings/blocked'
      preLoaderRoute: typeof SettingsBlockedRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/serials/$tmdbId': {
      id: '/serials/$tmdbId'
      path: '/serials/$tmdbId'
      fullPath: '/serials/$tmdbId'
      preLoaderRoute: typeof SerialsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/$mbid': {
      id: '/music/$mbid'
      path: '/music/$mbid'
      fullPath: '/music/$mbid'
      preLoaderRoute: typeof MusicMbidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$tmdbId': {
      id: '/films/$tmdbId'
      path: '/films/$tmdbId'
      fullPath: '/films/$tmdbId'
      preLoaderRoute: typeof FilmsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/$slug': {
      id: '/director/$slug'
      path: '/director/$slug'
      fullPath: '/director/$slug'
      preLoaderRoute: typeof DirectorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/$tmdbId': {
      id: '/cinema/$tmdbId'
      path: '/cinema/$tmdbId'
      fullPath: '/cinema/$tmdbId'
      preLoaderRoute: typeof CinemaTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$volumeId': {
      id: '/books/$volumeId'
      path: '/books/$volumeId'
      fullPath: '/books/$volumeId'
      preLoaderRoute: typeof BooksVolumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/$slug': {
      id: '/actor/$slug'
      path: '/actor/$slug'
      fullPath: '/actor/$slug'
      preLoaderRoute: typeof ActorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/register': {
      id: '/_authLayout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/forgot-password': {
      id: '/_authLayout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/reviews/$username/$reviewId': {
      id: '/reviews/$username/$reviewId'
      path: '/reviews/$username/$reviewId'
      fullPath: '/reviews/$username/$reviewId'
      preLoaderRoute: typeof ReviewsUsernameReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/watchlist': {
      id: '/profile/$username/watchlist'
      path: '/watchlist'
      fullPath: '/profile/$username/watchlist'
      preLoaderRoute: typeof ProfileUsernameWatchlistRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/watching': {
      id: '/profile/$username/watching'
      path: '/watching'
      fullPath: '/profile/$username/watching'
      preLoaderRoute: typeof ProfileUsernameWatchingRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/stats': {
      id: '/profile/$username/stats'
      path: '/stats'
      fullPath: '/profile/$username/stats'
      preLoaderRoute: typeof ProfileUsernameStatsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/reviews': {
      id: '/profile/$username/reviews'
      path: '/reviews'
      fullPath: '/profile/$username/reviews'
      preLoaderRoute: typeof ProfileUsernameReviewsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/liked': {
      id: '/profile/$username/liked'
      path: '/liked'
      fullPath: '/profile/$username/liked'
      preLoaderRoute: typeof ProfileUsernameLikedRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/films': {
      id: '/profile/$username/films'
      path: '/films'
      fullPath: '/profile/$username/films'
      preLoaderRoute: typeof ProfileUsernameFilmsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/diary': {
      id: '/profile/$username/diary'
      path: '/diary'
      fullPath: '/profile/$username/diary'
      preLoaderRoute: typeof ProfileUsernameDiaryRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/cinema': {
      id: '/profile/$username/cinema'
      path: '/cinema'
      fullPath: '/profile/$username/cinema'
      preLoaderRoute: typeof ProfileUsernameCinemaRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/music/tracks/$mbid': {
      id: '/music/tracks/$mbid'
      path: '/music/tracks/$mbid'
      fullPath: '/music/tracks/$mbid'
      preLoaderRoute: typeof MusicTracksMbidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/lists/': {
      id: '/profile/$username/lists/'
      path: '/lists'
      fullPath: '/profile/$username/lists/'
      preLoaderRoute: typeof ProfileUsernameListsIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/lists/new': {
      id: '/profile/$username/lists/new'
      path: '/lists/new'
      fullPath: '/profile/$username/lists/new'
      preLoaderRoute: typeof ProfileUsernameListsNewRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/lists/$listId/': {
      id: '/profile/$username/lists/$listId/'
      path: '/lists/$listId'
      fullPath: '/profile/$username/lists/$listId/'
      preLoaderRoute: typeof ProfileUsernameListsListIdIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/lists/$listId/edit': {
      id: '/profile/$username/lists/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/profile/$username/lists/$listId/edit'
      preLoaderRoute: typeof ProfileUsernameListsListIdEditRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsBlockedRoute: typeof SettingsBlockedRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsFavoritesRoute: typeof SettingsFavoritesRoute
  SettingsGenresRoute: typeof SettingsGenresRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsBlockedRoute: SettingsBlockedRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsFavoritesRoute: SettingsFavoritesRoute,
  SettingsGenresRoute: SettingsGenresRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameCinemaRoute: typeof ProfileUsernameCinemaRoute
  ProfileUsernameDiaryRoute: typeof ProfileUsernameDiaryRoute
  ProfileUsernameFilmsRoute: typeof ProfileUsernameFilmsRoute
  ProfileUsernameLikedRoute: typeof ProfileUsernameLikedRoute
  ProfileUsernameReviewsRoute: typeof ProfileUsernameReviewsRoute
  ProfileUsernameStatsRoute: typeof ProfileUsernameStatsRoute
  ProfileUsernameWatchingRoute: typeof ProfileUsernameWatchingRoute
  ProfileUsernameWatchlistRoute: typeof ProfileUsernameWatchlistRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernameListsNewRoute: typeof ProfileUsernameListsNewRoute
  ProfileUsernameListsIndexRoute: typeof ProfileUsernameListsIndexRoute
  ProfileUsernameListsListIdEditRoute: typeof ProfileUsernameListsListIdEditRoute
  ProfileUsernameListsListIdIndexRoute: typeof ProfileUsernameListsListIdIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameCinemaRoute: ProfileUsernameCinemaRoute,
  ProfileUsernameDiaryRoute: ProfileUsernameDiaryRoute,
  ProfileUsernameFilmsRoute: ProfileUsernameFilmsRoute,
  ProfileUsernameLikedRoute: ProfileUsernameLikedRoute,
  ProfileUsernameReviewsRoute: ProfileUsernameReviewsRoute,
  ProfileUsernameStatsRoute: ProfileUsernameStatsRoute,
  ProfileUsernameWatchingRoute: ProfileUsernameWatchingRoute,
  ProfileUsernameWatchlistRoute: ProfileUsernameWatchlistRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernameListsNewRoute: ProfileUsernameListsNewRoute,
  ProfileUsernameListsIndexRoute: ProfileUsernameListsIndexRoute,
  ProfileUsernameListsListIdEditRoute: ProfileUsernameListsListIdEditRoute,
  ProfileUsernameListsListIdIndexRoute: ProfileUsernameListsListIdIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DeveloperRoute: DeveloperRoute,
  SetupSecurityQuestionRoute: SetupSecurityQuestionRoute,
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  ActorSlugRoute: ActorSlugRoute,
  BooksVolumeIdRoute: BooksVolumeIdRoute,
  CinemaTmdbIdRoute: CinemaTmdbIdRoute,
  DirectorSlugRoute: DirectorSlugRoute,
  FilmsTmdbIdRoute: FilmsTmdbIdRoute,
  MusicMbidRoute: MusicMbidRoute,
  SerialsTmdbIdRoute: SerialsTmdbIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  CinemaIndexRoute: CinemaIndexRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  MusicIndexRoute: MusicIndexRoute,
  SerialsIndexRoute: SerialsIndexRoute,
  MusicTracksMbidRoute: MusicTracksMbidRoute,
  ReviewsUsernameReviewIdRoute: ReviewsUsernameReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
