export {
  createSeriesLog,
  getSeriesArchive,
  getSeriesByTmdbId,
  getSeriesDetail,
  getSeriesInteraction,
  getSeriesSeasonDetail,
  getTrendingSeries,
  searchSeries,
  updateSeriesInteraction,
} from "./api/requests";

export type {
  CachedSeries,
  CreateSeriesLogInput,
  CreateSeriesLogResponse,
  QueryRequestOptions,
  SerialArchiveInput,
  SerialArchiveItem,
  SerialArchivePeriod,
  SerialArchiveResponse,
  SerialArchiveSort,
  SerialDetailInput,
  SerialDetailResponse,
  SerialDetailReviewSort,
  SerialInteraction,
  SerialSeasonDetailResponse,
  TmdbSearchSeries,
  TrendingSeries,
  UpdateSerialInteractionInput,
} from "./api/types";
