import type { Express } from "express";
import listsRouter from "../../modules/lists/lists.routes";
import peopleRouter from "../../modules/people/people.routes";
import diaryRouter from "../../modules/diary/diary.routes";
import usersRouter from "../../modules/users/users.routes";
import reviewsRouter from "../../modules/reviews/reviews.routes";
import socialRouter from "../../modules/social/social.routes";
import interactionsRouter from "../../modules/interactions/interactions.routes";
import uploadsRouter from "../../modules/uploads/uploads.routes";
import publicRouter from "../../modules/public/public.routes";
import postsRouter from "../../modules/posts/posts.routes";
import dataTransferRouter from "../../modules/data-transfer/data-transfer.routes";
import searchRouter from "../../modules/search/search.routes";
import moderationRouter from "../../modules/moderation/moderation.routes";
import notificationsRouter from "../../modules/notifications/notifications.routes";
import reportsRouter from "../../modules/reports/reports.routes";
import adminRouter from "../../modules/admin/admin.routes";
import authRouter from "../../modules/auth/auth.routes";

export const registerRoutes = (app: Express): void => {
  app.use("/api/auth", authRouter);
  app.use("/api/search", searchRouter);
  app.use("/api/moderation", moderationRouter);
  app.use("/api/notifications", notificationsRouter);
  app.use("/api/reports", reportsRouter);
  app.use("/api/admin", adminRouter);
  app.use("/api/people", peopleRouter);
  app.use("/api/diary", diaryRouter);
  app.use("/api/users", usersRouter);
  app.use("/api/reviews", reviewsRouter);
  app.use("/api/social", socialRouter);
  app.use("/api/interactions", interactionsRouter);
  app.use("/api/uploads", uploadsRouter);
  app.use("/api/public", publicRouter);
  app.use("/api/posts", postsRouter);
  app.use("/api/lists", listsRouter);
  app.use("/api/data", dataTransferRouter);
};
