/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SerialsIndexRouteImport } from './routes/serials/index'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as CinemaIndexRouteImport } from './routes/cinema/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsGenresRouteImport } from './routes/settings/genres'
import { Route as SettingsFavoritesRouteImport } from './routes/settings/favorites'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as SerialsTmdbIdRouteImport } from './routes/serials/$tmdbId'
import { Route as FilmsTmdbIdRouteImport } from './routes/films/$tmdbId'
import { Route as DirectorSlugRouteImport } from './routes/director/$slug'
import { Route as CinemaTmdbIdRouteImport } from './routes/cinema/$tmdbId'
import { Route as ActorSlugRouteImport } from './routes/actor/$slug'
import { Route as ProfileUsernameRouteRouteImport } from './routes/profile/$username/route'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ReviewsUsernameReviewIdRouteImport } from './routes/reviews/$username/$reviewId'
import { Route as ProfileUsernameWatchlistRouteImport } from './routes/profile/$username/watchlist'
import { Route as ProfileUsernameReviewsRouteImport } from './routes/profile/$username/reviews'
import { Route as ProfileUsernameLikedRouteImport } from './routes/profile/$username/liked'
import { Route as ProfileUsernameFilmsRouteImport } from './routes/profile/$username/films'
import { Route as ProfileUsernameDiaryRouteImport } from './routes/profile/$username/diary'
import { Route as ProfileUsernameCinemaRouteImport } from './routes/profile/$username/cinema'
import { Route as ProfileUsernameListsIndexRouteImport } from './routes/profile/$username/lists/index'
import { Route as ProfileUsernameListsListIdRouteImport } from './routes/profile/$username/lists/$listId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SerialsIndexRoute = SerialsIndexRouteImport.update({
  id: '/serials/',
  path: '/serials/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaIndexRoute = CinemaIndexRouteImport.update({
  id: '/cinema/',
  path: '/cinema/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsGenresRoute = SettingsGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFavoritesRoute = SettingsFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SerialsTmdbIdRoute = SerialsTmdbIdRouteImport.update({
  id: '/serials/$tmdbId',
  path: '/serials/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsTmdbIdRoute = FilmsTmdbIdRouteImport.update({
  id: '/films/$tmdbId',
  path: '/films/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorSlugRoute = DirectorSlugRouteImport.update({
  id: '/director/$slug',
  path: '/director/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaTmdbIdRoute = CinemaTmdbIdRouteImport.update({
  id: '/cinema/$tmdbId',
  path: '/cinema/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorSlugRoute = ActorSlugRouteImport.update({
  id: '/actor/$slug',
  path: '/actor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRouteRoute = ProfileUsernameRouteRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ReviewsUsernameReviewIdRoute = ReviewsUsernameReviewIdRouteImport.update({
  id: '/reviews/$username/$reviewId',
  path: '/reviews/$username/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameWatchlistRoute =
  ProfileUsernameWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameReviewsRoute = ProfileUsernameReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameLikedRoute = ProfileUsernameLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameFilmsRoute = ProfileUsernameFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameDiaryRoute = ProfileUsernameDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameCinemaRoute = ProfileUsernameCinemaRouteImport.update({
  id: '/cinema',
  path: '/cinema',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameListsIndexRoute =
  ProfileUsernameListsIndexRouteImport.update({
    id: '/lists/',
    path: '/lists/',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)
const ProfileUsernameListsListIdRoute =
  ProfileUsernameListsListIdRouteImport.update({
    id: '/lists/$listId',
    path: '/lists/$listId',
    getParentRoute: () => ProfileUsernameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/actor/$slug': typeof ActorSlugRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/cinema/': typeof CinemaIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/serials/': typeof SerialsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/actor/$slug': typeof ActorSlugRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin': typeof AdminIndexRoute
  '/cinema': typeof CinemaIndexRoute
  '/films': typeof FilmsIndexRoute
  '/serials': typeof SerialsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists': typeof ProfileUsernameListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/developer': typeof DeveloperRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/actor/$slug': typeof ActorSlugRoute
  '/cinema/$tmdbId': typeof CinemaTmdbIdRoute
  '/director/$slug': typeof DirectorSlugRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/serials/$tmdbId': typeof SerialsTmdbIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/favorites': typeof SettingsFavoritesRoute
  '/settings/genres': typeof SettingsGenresRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/cinema/': typeof CinemaIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/serials/': typeof SerialsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/profile/$username/cinema': typeof ProfileUsernameCinemaRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/liked': typeof ProfileUsernameLikedRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/watchlist': typeof ProfileUsernameWatchlistRoute
  '/reviews/$username/$reviewId': typeof ReviewsUsernameReviewIdRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/developer'
    | '/login'
    | '/register'
    | '/profile/$username'
    | '/actor/$slug'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin/'
    | '/cinema/'
    | '/films/'
    | '/serials/'
    | '/settings/'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username/'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer'
    | '/login'
    | '/register'
    | '/actor/$slug'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin'
    | '/cinema'
    | '/films'
    | '/serials'
    | '/settings'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/developer'
    | '/login'
    | '/register'
    | '/profile/$username'
    | '/actor/$slug'
    | '/cinema/$tmdbId'
    | '/director/$slug'
    | '/films/$tmdbId'
    | '/serials/$tmdbId'
    | '/settings/auth'
    | '/settings/favorites'
    | '/settings/genres'
    | '/settings/profile'
    | '/settings/theme'
    | '/admin/'
    | '/cinema/'
    | '/films/'
    | '/serials/'
    | '/settings/'
    | '/profile/$username/cinema'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/liked'
    | '/profile/$username/reviews'
    | '/profile/$username/watchlist'
    | '/reviews/$username/$reviewId'
    | '/profile/$username/'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  DeveloperRoute: typeof DeveloperRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  ActorSlugRoute: typeof ActorSlugRoute
  CinemaTmdbIdRoute: typeof CinemaTmdbIdRoute
  DirectorSlugRoute: typeof DirectorSlugRoute
  FilmsTmdbIdRoute: typeof FilmsTmdbIdRoute
  SerialsTmdbIdRoute: typeof SerialsTmdbIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CinemaIndexRoute: typeof CinemaIndexRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  SerialsIndexRoute: typeof SerialsIndexRoute
  ReviewsUsernameReviewIdRoute: typeof ReviewsUsernameReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/serials/': {
      id: '/serials/'
      path: '/serials'
      fullPath: '/serials/'
      preLoaderRoute: typeof SerialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/': {
      id: '/cinema/'
      path: '/cinema'
      fullPath: '/cinema/'
      preLoaderRoute: typeof CinemaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/genres': {
      id: '/settings/genres'
      path: '/genres'
      fullPath: '/settings/genres'
      preLoaderRoute: typeof SettingsGenresRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/favorites': {
      id: '/settings/favorites'
      path: '/favorites'
      fullPath: '/settings/favorites'
      preLoaderRoute: typeof SettingsFavoritesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/serials/$tmdbId': {
      id: '/serials/$tmdbId'
      path: '/serials/$tmdbId'
      fullPath: '/serials/$tmdbId'
      preLoaderRoute: typeof SerialsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$tmdbId': {
      id: '/films/$tmdbId'
      path: '/films/$tmdbId'
      fullPath: '/films/$tmdbId'
      preLoaderRoute: typeof FilmsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director/$slug': {
      id: '/director/$slug'
      path: '/director/$slug'
      fullPath: '/director/$slug'
      preLoaderRoute: typeof DirectorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/$tmdbId': {
      id: '/cinema/$tmdbId'
      path: '/cinema/$tmdbId'
      fullPath: '/cinema/$tmdbId'
      preLoaderRoute: typeof CinemaTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actor/$slug': {
      id: '/actor/$slug'
      path: '/actor/$slug'
      fullPath: '/actor/$slug'
      preLoaderRoute: typeof ActorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/reviews/$username/$reviewId': {
      id: '/reviews/$username/$reviewId'
      path: '/reviews/$username/$reviewId'
      fullPath: '/reviews/$username/$reviewId'
      preLoaderRoute: typeof ReviewsUsernameReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/watchlist': {
      id: '/profile/$username/watchlist'
      path: '/watchlist'
      fullPath: '/profile/$username/watchlist'
      preLoaderRoute: typeof ProfileUsernameWatchlistRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/reviews': {
      id: '/profile/$username/reviews'
      path: '/reviews'
      fullPath: '/profile/$username/reviews'
      preLoaderRoute: typeof ProfileUsernameReviewsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/liked': {
      id: '/profile/$username/liked'
      path: '/liked'
      fullPath: '/profile/$username/liked'
      preLoaderRoute: typeof ProfileUsernameLikedRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/films': {
      id: '/profile/$username/films'
      path: '/films'
      fullPath: '/profile/$username/films'
      preLoaderRoute: typeof ProfileUsernameFilmsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/diary': {
      id: '/profile/$username/diary'
      path: '/diary'
      fullPath: '/profile/$username/diary'
      preLoaderRoute: typeof ProfileUsernameDiaryRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/cinema': {
      id: '/profile/$username/cinema'
      path: '/cinema'
      fullPath: '/profile/$username/cinema'
      preLoaderRoute: typeof ProfileUsernameCinemaRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/lists/': {
      id: '/profile/$username/lists/'
      path: '/lists'
      fullPath: '/profile/$username/lists/'
      preLoaderRoute: typeof ProfileUsernameListsIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/lists/$listId': {
      id: '/profile/$username/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/profile/$username/lists/$listId'
      preLoaderRoute: typeof ProfileUsernameListsListIdRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsFavoritesRoute: typeof SettingsFavoritesRoute
  SettingsGenresRoute: typeof SettingsGenresRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsFavoritesRoute: SettingsFavoritesRoute,
  SettingsGenresRoute: SettingsGenresRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameCinemaRoute: typeof ProfileUsernameCinemaRoute
  ProfileUsernameDiaryRoute: typeof ProfileUsernameDiaryRoute
  ProfileUsernameFilmsRoute: typeof ProfileUsernameFilmsRoute
  ProfileUsernameLikedRoute: typeof ProfileUsernameLikedRoute
  ProfileUsernameReviewsRoute: typeof ProfileUsernameReviewsRoute
  ProfileUsernameWatchlistRoute: typeof ProfileUsernameWatchlistRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernameListsListIdRoute: typeof ProfileUsernameListsListIdRoute
  ProfileUsernameListsIndexRoute: typeof ProfileUsernameListsIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameCinemaRoute: ProfileUsernameCinemaRoute,
  ProfileUsernameDiaryRoute: ProfileUsernameDiaryRoute,
  ProfileUsernameFilmsRoute: ProfileUsernameFilmsRoute,
  ProfileUsernameLikedRoute: ProfileUsernameLikedRoute,
  ProfileUsernameReviewsRoute: ProfileUsernameReviewsRoute,
  ProfileUsernameWatchlistRoute: ProfileUsernameWatchlistRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernameListsListIdRoute: ProfileUsernameListsListIdRoute,
  ProfileUsernameListsIndexRoute: ProfileUsernameListsIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  DeveloperRoute: DeveloperRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  ActorSlugRoute: ActorSlugRoute,
  CinemaTmdbIdRoute: CinemaTmdbIdRoute,
  DirectorSlugRoute: DirectorSlugRoute,
  FilmsTmdbIdRoute: FilmsTmdbIdRoute,
  SerialsTmdbIdRoute: SerialsTmdbIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CinemaIndexRoute: CinemaIndexRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  SerialsIndexRoute: SerialsIndexRoute,
  ReviewsUsernameReviewIdRoute: ReviewsUsernameReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
