/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsIndexRouteImport } from './routes/films/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FilmsTmdbIdRouteImport } from './routes/films/$tmdbId'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as ProfileUsernameReviewsRouteImport } from './routes/profile/$username/reviews'
import { Route as ProfileUsernameFilmsRouteImport } from './routes/profile/$username/films'
import { Route as ProfileUsernameDiaryRouteImport } from './routes/profile/$username/diary'
import { Route as ProfileUsernameListsIndexRouteImport } from './routes/profile/$username/lists/index'
import { Route as ProfileUsernameListsListIdRouteImport } from './routes/profile/$username/lists/$listId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIndexRoute = FilmsIndexRouteImport.update({
  id: '/films/',
  path: '/films/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsTmdbIdRoute = FilmsTmdbIdRouteImport.update({
  id: '/films/$tmdbId',
  path: '/films/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/profile/$username/',
  path: '/profile/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameReviewsRoute = ProfileUsernameReviewsRouteImport.update({
  id: '/profile/$username/reviews',
  path: '/profile/$username/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameFilmsRoute = ProfileUsernameFilmsRouteImport.update({
  id: '/profile/$username/films',
  path: '/profile/$username/films',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameDiaryRoute = ProfileUsernameDiaryRouteImport.update({
  id: '/profile/$username/diary',
  path: '/profile/$username/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameListsIndexRoute =
  ProfileUsernameListsIndexRouteImport.update({
    id: '/profile/$username/lists/',
    path: '/profile/$username/lists/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileUsernameListsListIdRoute =
  ProfileUsernameListsListIdRouteImport.update({
    id: '/profile/$username/lists/$listId',
    path: '/profile/$username/lists/$listId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/admin/': typeof AdminIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/admin': typeof AdminIndexRoute
  '/films': typeof FilmsIndexRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists': typeof ProfileUsernameListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/films/$tmdbId': typeof FilmsTmdbIdRoute
  '/admin/': typeof AdminIndexRoute
  '/films/': typeof FilmsIndexRoute
  '/profile/$username/diary': typeof ProfileUsernameDiaryRoute
  '/profile/$username/films': typeof ProfileUsernameFilmsRoute
  '/profile/$username/reviews': typeof ProfileUsernameReviewsRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
  '/profile/$username/lists/$listId': typeof ProfileUsernameListsListIdRoute
  '/profile/$username/lists/': typeof ProfileUsernameListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/films/$tmdbId'
    | '/admin/'
    | '/films/'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/reviews'
    | '/profile/$username/'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/films/$tmdbId'
    | '/admin'
    | '/films'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/reviews'
    | '/profile/$username'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/films/$tmdbId'
    | '/admin/'
    | '/films/'
    | '/profile/$username/diary'
    | '/profile/$username/films'
    | '/profile/$username/reviews'
    | '/profile/$username/'
    | '/profile/$username/lists/$listId'
    | '/profile/$username/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  FilmsTmdbIdRoute: typeof FilmsTmdbIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FilmsIndexRoute: typeof FilmsIndexRoute
  ProfileUsernameDiaryRoute: typeof ProfileUsernameDiaryRoute
  ProfileUsernameFilmsRoute: typeof ProfileUsernameFilmsRoute
  ProfileUsernameReviewsRoute: typeof ProfileUsernameReviewsRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
  ProfileUsernameListsListIdRoute: typeof ProfileUsernameListsListIdRoute
  ProfileUsernameListsIndexRoute: typeof ProfileUsernameListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/': {
      id: '/films/'
      path: '/films'
      fullPath: '/films/'
      preLoaderRoute: typeof FilmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$tmdbId': {
      id: '/films/$tmdbId'
      path: '/films/$tmdbId'
      fullPath: '/films/$tmdbId'
      preLoaderRoute: typeof FilmsTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/reviews': {
      id: '/profile/$username/reviews'
      path: '/profile/$username/reviews'
      fullPath: '/profile/$username/reviews'
      preLoaderRoute: typeof ProfileUsernameReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/films': {
      id: '/profile/$username/films'
      path: '/profile/$username/films'
      fullPath: '/profile/$username/films'
      preLoaderRoute: typeof ProfileUsernameFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/diary': {
      id: '/profile/$username/diary'
      path: '/profile/$username/diary'
      fullPath: '/profile/$username/diary'
      preLoaderRoute: typeof ProfileUsernameDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/lists/': {
      id: '/profile/$username/lists/'
      path: '/profile/$username/lists'
      fullPath: '/profile/$username/lists/'
      preLoaderRoute: typeof ProfileUsernameListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/lists/$listId': {
      id: '/profile/$username/lists/$listId'
      path: '/profile/$username/lists/$listId'
      fullPath: '/profile/$username/lists/$listId'
      preLoaderRoute: typeof ProfileUsernameListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  FilmsTmdbIdRoute: FilmsTmdbIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  FilmsIndexRoute: FilmsIndexRoute,
  ProfileUsernameDiaryRoute: ProfileUsernameDiaryRoute,
  ProfileUsernameFilmsRoute: ProfileUsernameFilmsRoute,
  ProfileUsernameReviewsRoute: ProfileUsernameReviewsRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
  ProfileUsernameListsListIdRoute: ProfileUsernameListsListIdRoute,
  ProfileUsernameListsIndexRoute: ProfileUsernameListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
